[package]
name = "sexpr-package"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
composite-guest = { path = "../../crates/composite-guest" }
composite-abi = { path = "../../crates/composite-abi", default-features = false }

[profile.release]
opt-level = "s"
lto = true
