[package]
name = "sexpr-package"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pack-guest = { path = "../../crates/pack-guest" }
pack-abi = { path = "../../crates/pack-abi", default-features = false }

[profile.release]
opt-level = "s"
lto = true
